routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome'); 
    //return ('pouet'); 
});
//remplaçait la route à la racine et
//dans le fichier FrontController on mettati ce que l'on voulait
//qui soit affiché
//Route::get('/','FrontController@index');

//afficher tous les livres:
Route::get('/boooks',function(){
    //$params = $slug;
    return App\Book::all();
});

Route::get('books',function(string $word1,string $word2){
    $search = $word1.' '.$word2;
    $result = App\Book::where('title','like',"%$search")->get();
    if(count($result)==0)
        return "sorry not found";
    return $result;
});
//si on veut passer un paramètre dynamique, on peut passer une variable
//dans la fonction
// :: => instance et sa méthode dans laravel
//route est instancié même si ça se voit pas
//pourquoi on peut pas faire
//Route::get('books/{id})'
// Route::get('book/{id}',function($id){
//     return App\Book::find($id);
// });

Route::get('/','FrontController@index');
//where définit la Regex qui permet de paramétrer le type d'uri que l'on aura
Route::get('book/{id}','FrontController@show')->where(['id' =>'[1-9][0-9]*']);

Route::get('author/{id}','FrontController@showBookByAuthor')->where(['id' =>'[1-9][0-9]*']);
Route::get('genre/{id}','FrontController@showBooksByGenre')->where(['id' =>'[1-9][0-9]*']);
Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
//routes pour login laravel avec commande
//php artisan make:auth
//Auth::routes();
//routes sécurisées
Route::resource('admin/book','BookController')->middleware('auth');

resources/views/partials/menu.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
<a class="navbar-brand" href="#">LARAVEL</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">        
        <ul class="navbar-nav">
            <li class="nav-item active"><a class="nav-link" href="{{url('')}}">Acceuil <span class="sr-only">(current)</span></a></li>
            @if(!Route::is('book.*'))
                @forelse($genres as $id=>$genre)
                <li class="nav-item"><a class="nav-link" href="{{url('genre',$id)}}">{{$genre}}</a></li>
                @empty
                <li>vide</li>
                @endforelse
            @endif
            @if(Auth::check())
            <li><a href="{{route('book.index')}}">Dashboard</a></li>
            <li><a 
                    href="{{route('logout')}}"
                    onclick="event.preventDfault();
                             document.getElementById('logout-form').submit();">
                    Logout
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{csrf_field()}}
                </form>
            </li>
            @else
            <li><a href="{{route('login')}}">Login</a></li>
            @endif
        </ul>

     
    </div>
</nav>