routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome'); 
    //return ('pouet'); 
});
//remplaçait la route à la racine et
//dans le fichier FrontController on mettati ce que l'on voulait
//qui soit affiché
//Route::get('/','FrontController@index');

//afficher tous les livres:
Route::get('/boooks',function(){
    //$params = $slug;
    return App\Book::all();
});

Route::get('books',function(string $word1,string $word2){
    $search = $word1.' '.$word2;
    $result = App\Book::where('title','like',"%$search")->get();
    if(count($result)==0)
        return "sorry not found";
    return $result;
});
//si on veut passer un paramètre dynamique, on peut passer une variable
//dans la fonction
// :: => instance et sa méthode dans laravel
//route est instancié même si ça se voit pas
//pourquoi on peut pas faire
//Route::get('books/{id})'
// Route::get('book/{id}',function($id){
//     return App\Book::find($id);
// });

Route::get('/','FrontController@index');
//where définit la Regex qui permet de paramétrer le type d'uri que l'on aura
Route::get('book/{id}','FrontController@show')->where(['id' =>'[1-9][0-9]*']);

Route::get('author/{id}','FrontController@showBookByAuthor')->where(['id' =>'[1-9][0-9]*']);
Route::get('genre/{id}','FrontController@showBooksByGenre')->where(['id' =>'[1-9][0-9]*']);
Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
//routes pour login laravel avec commande
//php artisan make:auth
//Auth::routes();
//routes sécurisées
Route::resource('admin/book','BookController')->middleware('auth');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = [
        'title','description','genre_id'
    ];
    public function setGenreIdAttribute($value){
        $this->attributes['genre_id'] = ($value == 0)? null : $value;
    }
    public function genre(){
        return $this->belongsTo(Genre::class);
    }
    public function authors(){
        //pourquoi pas hasMany?
        return $this->belongsToMany(Author::class);
    }
    //arv
    public function picture(){
        return $this->hasOne(Picture::class);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Book;//importer l'alias de la classe
use App\Author;
use App\Genre;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::paginate(5);
        //return "Dashboard";
        return view('back.book.index',compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $authors = Author::pluck('name','id')->all();
        $genres  = Genre::pluck('name','id')->all();
        return view('back.book.create',['authors'=>$authors,'genres'=>$genres]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //debuggage
        //dump($request->all()); die;

        /* validate 
        ** 'string|required' => pipé
        */
        $this->validate($request,[
            'title'       => 'string|required',
            'description' => 'string',
            'genre_id'    => 'integer',
            'authors.*'   => 'integer',
            'status'      => [ 'regex:/^mama|unpublished$/']
        ]);
        $book = Book::create($request->all());
        //dump($request->old('description'));die;
        // traitement des data
        //renvoie un objet qui permet de m'informer sur 
        //la ligne nouvellement crée dans la database
        //renvoie aussi les relations avec les tables 
        //liées à la ligne
        $authors = $request->authors; // array
        //dump($authors);
        //récupère l'id du nouveau book,
        //et crée un ligne dans la table authors_book
        //avec les clés secondaires
        $book->authors()->attach($authors);
       

        return redirect()->route('book.index')->with('message',[
            'type' => 'success',
            'content' => 'merci pour l\'ajout de votre livre'
        ]);
        //$book->title ="Un nouveau titre";

        //$book->save();
        // redirection
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    /**
     * A la place d'injecter un id, on peut directement
     * injecter le Book $book, et  le show va regarder l'URI 
     * (ex:'admin/book/17'),
     * prendre le numéro de book, et l'utiliser pour retourner
     * la view => 
     * A ne faire que en back, car en front on pourra modifier
     * les URI
     */
    public function show(Book $book)
    {
        //Solution commentée utilisable si $id dans l'argument
        //$book = Book::find($id);
        return view('back.book.show',compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        /* validate 
        ** 'string|required' => pipé
        */
        //dump($id);die;
        $book = Book::find($id);
        //dump($book->authors->pluck('id')->toArray());die;
        // $book->authors->map(function($author){
        //     echo $author->id." ";
        // });
        // die;
        //dump($book->id);die;
        $authors = Author::pluck('name','id')->all();
        $genres  = Genre::pluck('name','id')->all();
        return view('back.book.edit',['authors'=>$authors,'genres'=>$genres,'book'=>$book]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dump($errors);die;
        $this->validate($request,[
            'title'       => 'string|required',
            'description' => 'string',
            'genre_id'    => 'integer',
            'authors.*'   => 'integer',
            'status'      => [ 'regex:/^published|unpublished$/']
        ]);
        $book = Book::find($id);
        $book->update($request->all());
        $book->authors()->sync($request->authors);
        return redirect()->route('book.index')->with('message',[
            'type' => 'success',
            'content' => 'merci pour la modification de votre livre'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        //$book = Book::find($id);
        //$book->forceDelete();
    }
}

resources/views/back/book/create.blade.php
@extends('layouts.master')

@section('title')
Ajouter un livre
@endsection
@section('content')
@php /*
{{dump(json_encode($genres))}}
{{dump(json_encode($authors))}}
{-- authors[] permet de pusher des elements ds un tableau --}
*/
@endphp


<h1>Ajouter un livre</h1>
<form action="{{route('book.store')}}" method='post'>
    {{csrf_field()}}
    <div class="form-row">
        <div class="col-7">
            <label for="title">Titre :</label>
            <input type="text" name="title" value="{{old('title')}}" class="form-control" id="title" placeholder="Titre du livre">       
            @if($errors->has('title'))
            <span class="error bg-warning text-warning">{{$errors->first('title')}}</span>
            @endif
            @if($errors->first('title'))
                <div class="alert alert-danger">
                    <p>{{$errors->first('title')}}</p>
                </div>
            @endif

            <label for="bookDesc">Description :</label>
            <textarea name="description" class="form-control" id="bookDesc" rows="3" value="">{{old('description')}}</textarea>
            @if($errors->first('description'))
                <div class="alert alert-danger">
                    <p>{{$errors->first('description')}}</p>
                </div>
            @endif

            <label for="genre">Genre :</label>
            <select name="genre_id" id='genre' class="">

                <option value="0">No genre</option>
                @forelse($genres as $key=>$genre)
                    @if(old('genre_id') == $key)
                        <option value="{{$key}}" selected>{{$genre}}</option>
                    @else
                        <option value="{{$key}}">{{$genre}}</option>
                    @endif
                    @empty
                        <option>No Genre available</option>
                @endforelse
            </select>
            @if($errors->first('genre_id'))
                <div class="alert alert-danger">
                    <p>{{$errors->first('genre_id')}}</p>
                </div>
            @endif

            <h2>Choisissez un/des auteur(s)</h2>
            @forelse($authors as $id=>$name)
            <div class="form-check">
                    @if(is_array(old('authors')) && in_array($id, old('authors')))
                    <input name="authors[]" class="form-check-input" type="checkbox" value={{$id}} id="author{{$id}}" checked/>
                    @else
                    <input name="authors[]" class="form-check-input" type="checkbox" value={{$id}} id="author{{$id}}"/>
                    @endif
                <label class="form-check-label" for="author{{$id}}">
                    {{$name}}
                </label>
            </div>
            @empty
            <p>Pas d'auteur connu</p>
            @endforelse
            @if($errors->first('authors'))
                <div class="alert alert-danger">
                    <p>{{$errors->first('authors')}}</p>
                </div>
            @endif

        </div>
        <div class="col">
            <input type="submit" value="Ajouter un livre"/>      
            
            <legend class="col-form-label">Radios</legend>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="status" id="gridRadios1" value="published" checked>
                <label class="form-check-label" for="gridRadios1">
                    Publier
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="status" id="gridRadios2" value="unpublished">
                <label class="form-check-label" for="gridRadios2">
                    Dépublier
                </label>
            </div>
            @if($errors->first('status'))
                <div class="alert alert-danger">
                    <p>{{$errors->first('status')}}</p>
                </div>
            @endif

            <legend class="col-form-label">Choose an image</legend>
            <div class="custom-file">
                <input name="picture" type="file" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/back/book/edit.blade.php
@extends('layouts.master')

@section('title')
Editer un livre
@endsection
@section('content')
<h1>Editer un livre</h1>
<form action="{{route('book.update',$book->id)}}" method='post'>
    {{csrf_field()}}
    {{method_field('PUT')}}
    <div class="form-row">
        <div class="col-7">
            <label for="title">Titre :</label>
            <input type="text" name="title" value="{{$book->title}}" class="form-control" id="title" placeholder="{{$book->title}}">       
            @if($errors->has('title'))
            <span class="error bg-warning text-warning">{{$errors->first('title')}}</span>
            @endif
            @if($errors->first('title'))
                <div class="alert alert-danger">
                    <p>{{$errors->first('title')}}</p>
                </div>
            @endif

            <label for="bookDesc">Description :</label>
            <textarea name="description" class="form-control" id="bookDesc" rows="3" value="">{{$book->description}}</textarea>
            @if($errors->first('description'))
                <div class="alert alert-danger">
                    <p>{{$errors->first('description')}}</p>
                </div>
            @endif

            <label for="genre">Genre :</label>
            <select name="genre_id" id='genre' class="">
                <option value="0">No genre</option>
                @forelse($genres as $key=>$genre)
                    @if(isset($book->genre->id) && $book->genre->id == $key)
                    <option value="{{$key}}" selected>{{$genre}}</option>
                    @else
                    <option value="{{$key}}">{{$genre}}</option>
                    @endif
                    @empty
                        <option>No Genre available</option>
                @endforelse
            </select>
            @if($errors->first('genre_id'))
                <div class="alert alert-danger">
                    <p>{{$errors->first('genre_id')}}</p>
                </div>
            @endif

            <h2>Choisissez un/des auteur(s)</h2>
            @forelse($authors as $id=>$name)
            <div class="form-check">
                @if(in_array($id,$book->authors->pluck('id')->toArray()))
                <input name="authors[]" class="form-check-input" type="checkbox" value={{$id}} id="author{{$id}}" checked/>
                @else
                <input name="authors[]" class="form-check-input" type="checkbox" value={{$id}} id="author{{$id}}"/>
                @endif
                <label class="form-check-label" for="author{{$id}}">
                    {{$name}}
                </label>
            </div>
            @empty
            <p>Pas d'auteur connu</p>
            @endforelse
            @if($errors->first('authors'))
                <div class="alert alert-danger">
                    <p>{{$errors->first('authors')}}</p>
                </div>
            @endif

        </div>
        <div class="col">
            <input type="submit" value="Modifier un livre"/>      
            
            <legend class="col-form-label">Radios</legend>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="status" id="gridRadios1" value="published" checked>
                <label class="form-check-label" for="gridRadios1">
                    Publier
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="status" id="gridRadios2" value="unpublished">
                <label class="form-check-label" for="gridRadios2">
                    Dépublier
                </label>
            </div>
            @if($errors->first('status'))
                <div class="alert alert-danger">
                    <p>{{$errors->first('status')}}</p>
                </div>
            @endif

            <legend class="col-form-label">Choose an image</legend>
            <div class="custom-file">
                <input name="picture" type="file" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/back/book/index.blade.php
@extends('layouts.master')

@section('title')
Liste des livres
@endsection
@section('content')
<h1>Liste des livres</h1>
{{$books->links()}}
@include('back.partials.flash')
@include('back.partials.errors')

<a href="{{route('book.create')}}"><button type="button" class="btn btn-primary btn-lg">Ajouter un livre</button></a>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col"> Title</th>
            <th scope="col"> Author</th>
            <th scope="col"> Genre</th>
            <th scope="col"> Date de publication</th>
            <th scope="col"> Status</th>
            <th scope="col"> Edition</th>
            <th scope="col"> Show</th>
            <th scope="col"> Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach($books as $book)
        <tr>
            <td>
                <a href="{{route('book.show',$book->id)}}">{{$book->title}}</a>
            </td>
            <td>
                @forelse($book->authors as $author)
                    {{$author->name}} {{$author->id}}
                    @empty
                    livre auto-généré
                @endforelse
            </td>
            <td>{{$book->genre->name??'aucun genre'}}</td>
            <td>{{$book->created_at}}</td>
            <td>Status:TODO</td>
            <td >
                <a href="{{route('book.edit',$book->id)}}"> Edit </a>
            </td>
            <td><a href="{{route('book.show', $book->id)}}"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a></td>
            <td>
                <form class='delete' action="{{route('book.destroy',$book->id)}}" method="post">
                {{csrf_field()}}
                {{method_field('delete')}}
                <input class='delete' type='submit' value="delete"> 
                </form>
            </td>
        </tr>
        @endforeach
   </tbody>
</table>
{{$books->links()}}
@endsection

@section('scripts')
@parent
<script type="text/javascript" src="{{asset('js/confirm.js')}}"></script>
@endsection

resources/views/back/book/show.blade.php
@extends('layouts.master')

@section('title')
Livre
@endsection

@section('content')


    <div class="row">
        <div class="col col-lg-6">
            <h1>Title: {{ $book->title }} </h1>

            <ul>
                <li>{{ __('book.category') }} {{$book->genre->name??'aucun genre'}}</li>
                <li>Date de création : {{$book->created_at}}</li>
                <li>Date de mise à jour : {{$book->updated_at}}</li>
                <li>Status:todo</li>
            </ul>

            <h3>Author(s)</h3>
            <ul>
            @forelse($book->authors as $author)
                <li><a href="{{url('author',$author->id)}}">{{$author->name}}</a></li>
                @empty
                <p>livre auto-généré</p>
            @endforelse
            </ul>
        </div>
        @if($book->picture)
            <div class="col"><img src="{{asset('images/'.$book->picture->link)}}" alt="{{$book->picture->title}}"></div>
        @endif
    </div>

@endsection